### ISSUE TITLE
Issue running training

### ISSUE THREAD

**Issue by cjchristopher** [ryderling/MalGraph#4]
Hi @ryderling
Having managed to sequence a dataset from IDA and create what I think is a valid vocab file, the code itself seems to have an issue now in the multithreading/data parallelism - could you please advise on this error?
```

-------------------------------------------------- start of 0-epoch, init best_auc=0.0, start time=2022-10-23@22:05:49 --------------------------------------------------
The local device = cuda:0 among 1 nprocs in the 0-th epoch.
reading _batch from local_rank=0:   0%|                       | 0/40 [00:00<?, ?it/s]
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/myuser/MalGraph/malgraph/lib/python3.8/site-packages/prefetch_generator/__init__.py", line 80, in run
    for item in self.generator:
  File "/home/myuser/MalGraph/malgraph/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 652, in __next__
    data = self._next_data()
  File "/home/myuser/MalGraph/malgraph/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 692, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/myuser/MalGraph/malgraph/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/myuser/MalGraph/malgraph/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/myuser/MalGraph/malgraph/lib/python3.8/site-packages/torch_geometric/data/dataset.py", line 197, in __getitem__
    data = self.get(self.indices()[idx])
  File "/home/myuser/MalGraph/malgraph/lib/python3.8/site-packages/torch_geometric/data/dataset.py", line 90, in indices
    return range(self.len()) if self._indices is None else self._indices
  File "/home/myuser/MalGraph/malgraph/lib/python3.8/site-packages/torch_geometric/data/dataset.py", line 62, in len
    raise NotImplementedError
NotImplementedError
```

**Comment by cjchristopher** [comment]
I fixed the above issue by adding:

```
def __getitem__(self, idx):
    return self.get(idx)
```

to the definition of MalwareDetectionDataset

However, this causes another issue further downstream in the model itself:
```
File "/home/myuser/Malgraph/malgraph/lib/python3.8/site-packages/torch-geometric/nn/dense/linear.py", line 118, in forward)
    return F.linear(x, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (132925x7 and 11x200)
```

This is resolved by changing the yaml config to only expect 7 node features (as opposed to 11) however now I have other runtime errors deeper in the model:

```
File "/home/myuser/Malgraph/src/HierarchicalGraphModel.py, line 200, in forward
    idx_function_edge = torch.tensor(bt_all_function_edges[idx_batch], dtype=torch.long
RuntimeError: Overflow when unpacking long
```
