### ISSUE TITLE
Reproducing help wanted

### ISSUE THREAD

**Issue by KennenH** [ryderling/MalGraph#7]
Hi, Author

I'm running MalGraph on Ubuntu18.04(Python 3.8 Cuda  11.2), RTX 3080, and I got an error below, I have no idea about how to fix this and the problem has been stuck me for three days.

I downloaded datasets from VirusShare and labelled them with VirusTotal api, processed all pe files according to README.md and finally obtained about 2000 samples from 8 families. Then I used PreProcess.py to generate PyTorch_Geometric data object for all samples with their corresponding family labels. 

below are the console output and error stacktrace

> [2023-08-11 12:46:55,540][DistTrainModel.py][WARNING] - Hydra's Current Working Directory: /tmp/MalGraph/src/outputs/2023-08-11/12-46-55
> +-------+--------------------------+-------------------------------------------+
> | Index | Parameters               |                  Values                   |
> +-------+--------------------------+-------------------------------------------+
> | 0     | external_func_vocab_file | /root/autodl-tmp/train_external_function_ |
> |       |                          |             name_vocab.jsonl              |
> +-------+--------------------------+-------------------------------------------+
> | 1     | max_epochs               |                    10                     |
> +-------+--------------------------+-------------------------------------------+
> | 2     | max_vocab_size           |                   10000                   |
> +-------+--------------------------+-------------------------------------------+
> | 3     | processed_files_path     |             /root/autodl-tmp              |
> +-------+--------------------------+-------------------------------------------+
> | 4     | test_bs                  |                    32                     |
> +-------+--------------------------+-------------------------------------------+
> | 5     | train_bs                 |                    16                     |
> +-------+--------------------------+-------------------------------------------+
> +-------+-----------------+-----------------+
> | Index | Parameters      |     Values      |
> 
> +-------+-----------------+-----------------+
> | 0     | ablation_models |      Full       |
> +-------+-----------------+-----------------+
> | 1     | acfg_init_dims  |       11        |
> +-------+-----------------+-----------------+
> | 2     | cfg_filters     |     200-200     |
> +-------+-----------------+-----------------+
> | 3     | dropout_rate    |    0.200000     |
> +-------+-----------------+-----------------+
> | 4     | fcg_filters     |     200-200     |
> +-------+-----------------+-----------------+
> | 5     | gnn_type        |    GraphSAGE    |
> +-------+-----------------+-----------------+
> | 6     | number_classes  |        8        |
> +-------+-----------------+-----------------+
> | 7     | pool_type       | global_max_pool |
> +-------+-----------------+-----------------+
> +-------+-----------------+----------+
> | Index | Parameters      |  Values  |
> +-------+-----------------+----------+
> | 0     | learning_anneal | 1.100000 |
> +-------+-----------------+----------+
> | 1     | lr              | 0.001000 |
> +-------+-----------------+----------+
> | 2     | optimizer_name  |  AdamW   |
> +-------+-----------------+----------+
> | 3     | weight_decay    | 0.000010 |
> +-------+-----------------+----------+
> +-------+-----------------------------------+----------------------------------+
> | Index | Parameters                        |              Values              |
> +-------+-----------------------------------+----------------------------------+
> | 0     | Hydra's Current Working Directory | /tmp/MalGraph/src/outputs/2023-0 |
> |       |                                   |          8-11/12-46-55           |
> +-------+-----------------------------------+----------------------------------+
> | 1     | log result file                   | /tmp/MalGraph/src/outputs/2023-0 |
> |       |                                   | 8-11/12-46-55/Full_GraphSAGE_glo |
> |       |                                   | bal_max_pool_ACFG_200-200_FCG_20 |
> |       |                                   | 0-200_Epoch_10_TrainBS_16_LR_0.0 |
> |       |                                   |   01_Time_20230811_124655.txt    |
> +-------+-----------------------------------+----------------------------------+
> | 2     | only_test_path                    |               None               |
> +-------+-----------------------------------+----------------------------------+
> | 3     | seed                              |             19920208             |
> +-------+-----------------------------------+----------------------------------+
> [2023-08-11 12:46:55,543][DistTrainModel.py][INFO] - Total number of GPUs = 1
> /tmp/MalGraph/src/DistTrainModel.py:268: UserWarning: 
> The version_base parameter is not specified.
> Please specify a compatability version level, or None.
> Will assume defaults for version 1.1
>   @hydra.main(config_path="../configs/", config_name="default.yaml")
> Load frequency list from the file of /root/autodl-tmp/train_external_function_name_vocab.jsonl ... : 10000it [00:00, 302912.20it/s]
> creating vocab ... : 100%|█████████████| 10000/10000 [00:00<00:00, 12722.29it/s]
> <class 'str'> 200-200
> <class 'str'> 200-200
> DistributedDataParallel(
>   (module): HierarchicalGraphNeuralNetwork(
>     (CFG_gnn_1): SAGEConv(11, 200, aggr=mean)
>     (CFG_gnn_2): SAGEConv(200, 200, aggr=mean)
>     (dropout): Dropout(p=0.2, inplace=False)
>     (external_embedding_layer): Embedding(10002, 200, padding_idx=1)
>     (FCG_gnn_1): SAGEConv(200, 200, aggr=mean)
>     (FCG_gnn_2): SAGEConv(200, 200, aggr=mean)
>     (pj1): Linear(in_features=200, out_features=100, bias=True)
>     (pj2): Linear(in_features=100, out_features=50, bias=True)
>     (pj3): Linear(in_features=50, out_features=1, bias=True)
>     (last_activation): Softmax(dim=1)
>   )
> )
> /root/miniconda3/envs/malgraph/lib/python3.8/site-packages/torch_geometric/deprecation.py:22: UserWarning: 'data.DataLoader' is deprecated, use 'loader.DataLoader' instead
>   warnings.warn(out)
> Training dataset=1170, sampler=1170, loader=74
> Validation dataset=148, sampler=148, loader=5
> 
> -------------------------------------------------- start of 0-epoch, init best_auc=0.0, start time=2023-08-11@12:46:59 --------------------------------------------------
> The local device = cuda:0 among 1 nprocs in the 0-th epoch.
> reading _batch from local_rank=0:   0%|                  | 0/74 [00:00<?, ?it/s]/root/miniconda3/envs/malgraph/lib/python3.8/site-packages/torch_geometric/utils/scatter.py:93: UserWarning: The usage of `scatter(reduce='max')` can be accelerated via the 'torch-scatter' package, but it was not found
>   warnings.warn(f"The usage of `scatter(reduce='{reduce}')` "
> /opt/conda/conda-bld/pytorch_1659484810403/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [19,0,0], thread: [3,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
> /opt/conda/conda-bld/pytorch_1659484810403/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [18,0,0], thread: [82,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
> /opt/conda/conda-bld/pytorch_1659484810403/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [19,0,0], thread: [46,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
> /opt/conda/conda-bld/pytorch_1659484810403/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [19,0,0], thread: [47,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
> /opt/conda/conda-bld/pytorch_1659484810403/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [19,0,0], thread: [48,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
> /opt/conda/conda-bld/pytorch_1659484810403/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [18,0,0], thread: [108,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
> /opt/conda/conda-bld/pytorch_1659484810403/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [18,0,0], thread: [120,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
> /opt/conda/conda-bld/pytorch_1659484810403/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [19,0,0], thread: [98,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
> /opt/conda/conda-bld/pytorch_1659484810403/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [19,0,0], thread: [104,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
> /opt/conda/conda-bld/pytorch_1659484810403/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [19,0,0], thread: [105,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
> /opt/conda/conda-bld/pytorch_1659484810403/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [19,0,0], thread: [114,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
> /opt/conda/conda-bld/pytorch_1659484810403/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [19,0,0], thread: [115,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
> /opt/conda/conda-bld/pytorch_1659484810403/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [19,0,0], thread: [86,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
> /opt/conda/conda-bld/pytorch_1659484810403/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [19,0,0], thread: [87,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
> /opt/conda/conda-bld/pytorch_1659484810403/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [19,0,0], thread: [95,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
> reading _batch from local_rank=0:   0%|                  | 0/74 [00:01<?, ?it/s]
> Error executing job with overrides: []
> Traceback (most recent call last):
>   File "/tmp/MalGraph/src/DistTrainModel.py", line 346, in <module>
>     main_app()
>   File "/root/miniconda3/envs/malgraph/lib/python3.8/site-packages/hydra/main.py", line 94, in decorated_main
>     _run_hydra(
>   File "/root/miniconda3/envs/malgraph/lib/python3.8/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
>     _run_app(
>   File "/root/miniconda3/envs/malgraph/lib/python3.8/site-packages/hydra/_internal/utils.py", line 457, in _run_app
>     run_and_report(
>   File "/root/miniconda3/envs/malgraph/lib/python3.8/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
>     raise ex
>   File "/root/miniconda3/envs/malgraph/lib/python3.8/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
>     return func()
>   File "/root/miniconda3/envs/malgraph/lib/python3.8/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
>     lambda: hydra.run(
>   File "/root/miniconda3/envs/malgraph/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 132, in run
>     _ = ret.return_value
>   File "/root/miniconda3/envs/malgraph/lib/python3.8/site-packages/hydra/core/utils.py", line 260, in return_value
>     raise self._return_value
>   File "/root/miniconda3/envs/malgraph/lib/python3.8/site-packages/hydra/core/utils.py", line 186, in run_job
>     ret.return_value = task_function(task_cfg)
>   File "/tmp/MalGraph/src/DistTrainModel.py", line 306, in main_app
>     torch_mp.spawn(main_train_worker, nprocs=num_gpus, args=(num_gpus, _train_params, _model_params, _optim_params, log, log_result_file,))
>   File "/root/miniconda3/envs/malgraph/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
>     return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
>   File "/root/miniconda3/envs/malgraph/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
>     while not context.join():
>   File "/root/miniconda3/envs/malgraph/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 160, in join
>     raise ProcessRaisedException(msg, error_index, failed_process.pid)
> torch.multiprocessing.spawn.ProcessRaisedException: 
> 
> -- Process 0 terminated with the following error:
> Traceback (most recent call last):
>   File "/root/miniconda3/envs/malgraph/lib/python3.8/site-packages/torch_geometric/nn/aggr/base.py", line 109, in __call__
>     return super().__call__(x, index, ptr, dim_size, dim, **kwargs)
>   File "/root/miniconda3/envs/malgraph/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/root/miniconda3/envs/malgraph/lib/python3.8/site-packages/torch_geometric/nn/aggr/basic.py", line 34, in forward
>     return self.reduce(x, index, ptr, dim_size, dim, reduce='mean')
>   File "/root/miniconda3/envs/malgraph/lib/python3.8/site-packages/torch_geometric/nn/aggr/base.py", line 155, in reduce
>     return scatter(x, index, dim, dim_size, reduce)
>   File "/root/miniconda3/envs/malgraph/lib/python3.8/site-packages/torch_geometric/utils/scatter.py", line 78, in scatter
>     count.scatter_add_(0, index, src.new_ones(src.size(dim)))
> RuntimeError: CUDA error: device-side assert triggered
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/root/miniconda3/envs/malgraph/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
>     fn(i, *args)
>   File "/tmp/MalGraph/src/DistTrainModel.py", line 250, in main_train_worker
>     smooth_avg_reduced_loss_list, best_auc = train_one_epoch(local_rank=local_rank, train_loader=train_loader, valid_loader=valid_loader, model=model, criterion=criterion,
>   File "/tmp/MalGraph/src/DistTrainModel.py", line 74, in train_one_epoch
>     train_batch_pred = model(real_local_batch=_real_batch, real_bt_positions=_position, bt_external_names=_external_list, bt_all_function_edges=_function_edges, local_device=local_device)
>   File "/root/miniconda3/envs/malgraph/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/root/miniconda3/envs/malgraph/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1008, in forward
>     output = self._run_ddp_forward(*inputs, **kwargs)
>   File "/root/miniconda3/envs/malgraph/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 969, in _run_ddp_forward
>     return module_to_run(*inputs[0], **kwargs[0])
>   File "/root/miniconda3/envs/malgraph/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/tmp/MalGraph/src/models/HierarchicalGraphModel.py", line 206, in forward
>     rtn_fcg_batch = self.forward_fcg_gnn(function_batch=fcg_batch)  # [batch_size, max_node_size, dim]
>   File "/tmp/MalGraph/src/models/HierarchicalGraphModel.py", line 145, in forward_fcg_gnn
>     out_x = getattr(self, 'FCG_gnn_{}'.format(i + 1))(x=in_x, edge_index=edge_index)
>   File "/root/miniconda3/envs/malgraph/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/root/miniconda3/envs/malgraph/lib/python3.8/site-packages/torch_geometric/nn/conv/sage_conv.py", line 131, in forward
>     out = self.propagate(edge_index, x=x, size=size)
>   File "/root/miniconda3/envs/malgraph/lib/python3.8/site-packages/torch_geometric/nn/conv/message_passing.py", line 484, in propagate
>     out = self.aggregate(out, **aggr_kwargs)
>   File "/root/miniconda3/envs/malgraph/lib/python3.8/site-packages/torch_geometric/nn/conv/message_passing.py", line 608, in aggregate
>     return self.aggr_module(inputs, index, ptr=ptr, dim_size=dim_size,
>   File "/root/miniconda3/envs/malgraph/lib/python3.8/site-packages/torch_geometric/nn/aggr/base.py", line 112, in __call__
>     if index.numel() > 0 and dim_size <= int(index.max()):
> RuntimeError: CUDA error: device-side assert triggered
> 
> 
> Process finished with exit code 1

I only figured out that the error statement is in HierarchicalGraphModel.py

`out_x = getattr(self, 'FCG_gnn_{}'.format(i + 1))(x=in_x, edge_index=edge_index)`

I hit a breakpoint and before executing this statement, parameters `in_x` of {Tensor:3137} and `edge_index`  of {Tensor:2} are

> tensor([[ 4.9432, 30.1366,  3.0779,  ..., 16.2154,  0.0000,  3.1581],
>         [ 1.3546,  5.2641,  2.3746,  ...,  3.6004,  0.7208,  2.3018],
>         [ 0.0000,  0.0000,  0.3557,  ...,  0.3267,  0.0000,  0.3677],
>         ...,
>         [ 0.0000,  0.0000,  0.0000,  ...,  0.1683,  0.0402,  0.1028],
>         [ 0.0000,  0.1101,  0.0000,  ...,  0.2590,  0.0000,  0.0000],
>         [ 0.0865,  0.0000,  0.1006,  ...,  0.4810,  0.0000,  0.8312]],
>        device='cuda:0', grad_fn=<CatBackward0>) 
> 

and
 

> tensor([[   0,    0,    0,  ..., 3092, 3092, 3092],
>         [   1,   19,   20,  ..., 3113, 3114, 3115]], device='cuda:0')
> 

respectively.

Would you please give me some possible suggestions, thanks for advance!

### **EDIT:**

I ran the same code on cpu(without .cuda()) and the error stacktrace is more clearer now

> Traceback (most recent call last):
> File "D:\Anaconda3\envs\pytorch\lib\site-packages\hydra_internal\utils.py", line 394, in _run_hydra
> _run_app(
> File "D:\Anaconda3\envs\pytorch\lib\site-packages\hydra_internal\utils.py", line 457, in _run_app
> run_and_report(
> File "D:\Anaconda3\envs\pytorch\lib\site-packages\hydra_internal\utils.py", line 223, in run_and_report
> raise ex
> File "D:\Anaconda3\envs\pytorch\lib\site-packages\hydra_internal\utils.py", line 220, in run_and_report
> return func()
> File "D:\Anaconda3\envs\pytorch\lib\site-packages\hydra_internal\utils.py", line 458, in
> lambda: hydra.run(
> File "D:\Anaconda3\envs\pytorch\lib\site-packages\hydra_internal\hydra.py", line 132, in run
> _ = ret.return_value
> File "D:\Anaconda3\envs\pytorch\lib\site-packages\hydra\core\utils.py", line 260, in return_value
> raise self._return_value
> File "D:\Anaconda3\envs\pytorch\lib\site-packages\hydra\core\utils.py", line 186, in run_job
> ret.return_value = task_function(task_cfg)
> File "D:/hkn/project_folder/MalGraph/src/DistTrainModel_mine.py", line 367, in main_app
> _valid_result = validate(valid_loader=valid_dataloader, model=model, criterion=criterion, evaluate_flag="DoubleCheckValidation", distributed=False, local_rank=None, nprocs=None, original_valid_length=len(valid_dataset), result_file=log_result_file, details=True)
> File "D:/hkn/project_folder/MalGraph/src/DistTrainModel_mine.py", line 146, in validate
> batch_pred = model(real_local_batch=_real_batch, real_bt_positions=_position, bt_external_names=_external_list, bt_all_function_edges=_function_edges, local_device=local_device)
> File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1130, in call_impl
> return forward_call(*input, **kwargs)
> File "D:\hkn\project_folder\MalGraph\src\models\HierarchicalGraphModel.py", line 206, in forward
> rtn_fcg_batch = self.forward_fcg_gnn(function_batch=fcg_batch) # [batch_size, max_node_size, dim]
> File "D:\hkn\project_folder\MalGraph\src\models\HierarchicalGraphModel.py", line 145, in forward_fcg_gnn
> out_x = getattr(self, 'FCG_gnn{}'.format(i + 1))(x=in_x, edge_index=edge_index)
> File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
> return forward_call(*input, **kwargs)
> File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch_geometric\nn\conv\sage_conv.py", line 131, in forward
> out = self.propagate(edge_index, x=x, size=size)
> File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch_geometric\nn\conv\message_passing.py", line 459, in propagate
> coll_dict = self._collect(self._user_args, edge_index, size,
> File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch_geometric\nn\conv\message_passing.py", line 336, in _collect
> data = self._lift(data, edge_index, dim)
> File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch_geometric\nn\conv\message_passing.py", line 275, in _lift
> raise IndexError(
> IndexError: Encountered an index error. Please ensure that all indices in 'edge_index' point to valid indices in the interval [0, 7585] (got interval [0, 7592])
> 
> Process finished with exit code 1

And the output of function_batch.validate() is:

> IndexError: Encountered an index error. Please ensure that all indices in 'edge_index' point to valid indices in the interval [0, 7585] (got interval [0, 7592])

So the problem is that indices of edge_index exceeds the length of tensor in_x

**Comment by KennenH** [comment]
I ran the same code on cpu(with .cuda()) and the error stacktrace is more clearer now

Traceback (most recent call last):
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\hydra\_internal\utils.py", line 394, in _run_hydra
    _run_app(
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\hydra\_internal\utils.py", line 457, in _run_app
    run_and_report(
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\hydra\_internal\utils.py", line 223, in run_and_report
    raise ex
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\hydra\_internal\utils.py", line 220, in run_and_report
    return func()
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\hydra\_internal\utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\hydra\_internal\hydra.py", line 132, in run
    _ = ret.return_value
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\hydra\core\utils.py", line 260, in return_value
    raise self._return_value
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\hydra\core\utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "D:/hkn/project_folder/MalGraph/src/DistTrainModel_mine.py", line 367, in main_app
    _valid_result = validate(valid_loader=valid_dataloader, model=model, criterion=criterion, evaluate_flag="DoubleCheckValidation", distributed=False, local_rank=None, nprocs=None, original_valid_length=len(valid_dataset), result_file=log_result_file, details=True)
  File "D:/hkn/project_folder/MalGraph/src/DistTrainModel_mine.py", line 146, in validate
    batch_pred = model(real_local_batch=_real_batch, real_bt_positions=_position, bt_external_names=_external_list, bt_all_function_edges=_function_edges, local_device=local_device)
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\hkn\project_folder\MalGraph\src\models\HierarchicalGraphModel.py", line 206, in forward
    rtn_fcg_batch = self.forward_fcg_gnn(function_batch=fcg_batch)  # [batch_size, max_node_size, dim]
  File "D:\hkn\project_folder\MalGraph\src\models\HierarchicalGraphModel.py", line 145, in forward_fcg_gnn
    out_x = getattr(self, 'FCG_gnn_{}'.format(i + 1))(x=in_x, edge_index=edge_index)
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch_geometric\nn\conv\sage_conv.py", line 131, in forward
    out = self.propagate(edge_index, x=x, size=size)
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch_geometric\nn\conv\message_passing.py", line 459, in propagate
    coll_dict = self._collect(self._user_args, edge_index, size,
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch_geometric\nn\conv\message_passing.py", line 336, in _collect
    data = self._lift(data, edge_index, dim)
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch_geometric\nn\conv\message_passing.py", line 275, in _lift
    raise IndexError(
IndexError: Encountered an index error. Please ensure that all indices in 'edge_index' point to valid indices in the interval [0, 7585] (got interval [0, 7592])

Process finished with exit code 1


So the problem is that indices of `edge_index` exceeds the length of tensor `in_x`
